/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AccountabilityRouteImport } from './routes/accountability'
import { Route as EstimateRouteImport } from './routes/estimate'
import { Route as AccountabilityTsxRouteImport } from './routes/accountability.tsx'
import { Route as IndexTsxRouteImport } from './routes/index.tsx'

const AccountabilityRoute = AccountabilityRouteImport.update({
  id: '/accountability',
  path: '/accountability',
  getParentRoute: () => rootRouteImport,
} as any)
const EstimateRoute = EstimateRouteImport.update({
  id: '/estimate',
  path: '/estimate',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountabilityTsxRoute = AccountabilityTsxRouteImport.update({
  id: '/tsx',
  path: '/tsx',
  getParentRoute: () => AccountabilityRoute,
} as any)
const IndexTsxRoute = IndexTsxRouteImport.update({
  id: '/index/tsx',
  path: '/index/tsx',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/accountability': typeof AccountabilityRouteWithChildren
  '/estimate': typeof EstimateRoute
  '/accountability/tsx': typeof AccountabilityTsxRoute
  '/index/tsx': typeof IndexTsxRoute
}
export interface FileRoutesByTo {
  '/accountability': typeof AccountabilityRouteWithChildren
  '/estimate': typeof EstimateRoute
  '/accountability/tsx': typeof AccountabilityTsxRoute
  '/index/tsx': typeof IndexTsxRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/accountability': typeof AccountabilityRouteWithChildren
  '/estimate': typeof EstimateRoute
  '/accountability/tsx': typeof AccountabilityTsxRoute
  '/index/tsx': typeof IndexTsxRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/accountability' | '/estimate' | '/accountability/tsx' | '/index/tsx'
  fileRoutesByTo: FileRoutesByTo
  to: '/accountability' | '/estimate' | '/accountability/tsx' | '/index/tsx'
  id:
    | '__root__'
    | '/accountability'
    | '/estimate'
    | '/accountability/tsx'
    | '/index/tsx'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AccountabilityRoute: typeof AccountabilityRouteWithChildren
  EstimateRoute: typeof EstimateRoute
  IndexTsxRoute: typeof IndexTsxRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/accountability': {
      id: '/accountability'
      path: '/accountability'
      fullPath: '/accountability'
      preLoaderRoute: typeof AccountabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estimate': {
      id: '/estimate'
      path: '/estimate'
      fullPath: '/estimate'
      preLoaderRoute: typeof EstimateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accountability/tsx': {
      id: '/accountability/tsx'
      path: '/tsx'
      fullPath: '/accountability/tsx'
      preLoaderRoute: typeof AccountabilityTsxRouteImport
      parentRoute: typeof AccountabilityRoute
    }
    '/index/tsx': {
      id: '/index/tsx'
      path: '/index/tsx'
      fullPath: '/index/tsx'
      preLoaderRoute: typeof IndexTsxRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AccountabilityRouteChildren {
  AccountabilityTsxRoute: typeof AccountabilityTsxRoute
}

const AccountabilityRouteChildren: AccountabilityRouteChildren = {
  AccountabilityTsxRoute: AccountabilityTsxRoute,
}

const AccountabilityRouteWithChildren = AccountabilityRoute._addFileChildren(
  AccountabilityRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AccountabilityRoute: AccountabilityRouteWithChildren,
  EstimateRoute: EstimateRoute,
  IndexTsxRoute: IndexTsxRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
